const express =require('express')

const router = express.Router()
const userSignUpController = require("../controller/userSignUp.js")
const userSignInController = require('../controller/userSignIn.js')
const userDetailsController= require('../controller/userDetails.js')
const authToken = require('../middleware/authToken.js')
const userLogout = require('../controller/userLogout.js')
const allUsers = require('../controller/allUsers.js')
const updateUser = require('../controller/updateUser.js')
const UploadProductController = require('../controller/uploadProduct.js')
const getProductController = require('../controller/getProduct.js')
const updateProductController = require('../controller/updateProduct.js')
const getCategoryProduct = require('../controller/getCategoryProduct.js')
const getCategoryWiseProduct = require('../controller/getCategoryWiseProduct.js')
const getProductDetails = require('../controller/getProductDetails.js')
const addToCartController = require('../controller/addtoCartController.js')
const countAddToCartProduct = require('../controller/countAddToCartProduct.js')
const addToCartViewProduct = require('../controller/addToCartViewProduct.js')
const updateAddToCartProduct = require('../controller/updateAddToCartProduct.js')
const deleteAddToCartProduct = require('../controller/deleteAddToCartProduct.js')
const searchProduct = require('../controller/searchProduct.js')
const filterProductController = require('../controller/filterProduct.js')
router.post("/signup",userSignUpController)
router.post("/signin",userSignInController)
router.get("/user-details",authToken,userDetailsController)
router.get('/logout',userLogout)

//admin panel 
router.get("/all-user",authToken,allUsers)
router.post("/update-user",authToken,updateUser)
// upload product
router.post("/upload-product",authToken, UploadProductController)
router.get("/get-product", getProductController)
router.post("/update-product",authToken,updateProductController)
router.get("/get-categoryProduct",getCategoryProduct)
router.post("/category-product",getCategoryWiseProduct)
router.post("/product-details",getProductDetails)
router.get("/search",searchProduct)
router.post("/filter-product",filterProductController)

router.post("/addtocart",authToken,addToCartController)
router.get("/countAddToCartProduct",authToken,countAddToCartProduct)
router.get("/view-card-product",authToken,addToCartViewProduct)
router.post("/update-cart-product",authToken,updateAddToCartProduct)
router.post("/delete-cart-product",authToken,deleteAddToCartProduct)
module.exports=router